# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

character_types = CharacterType.create([
	{name: 'Vampire', power_stat: 'Blood Potency', resource: 'Vitae', morality: 'Humanity', behavior_primary: 'Mask', behavior_secondary: 'Dirge', affiliation: 'Covenant', lineage: 'Clan', sublineage: 'Bloodline', question1: 'AGE: How old are you? How old do you look? How long have you been a vampire? Other than the obvious, how has your life changed since the Embrace?', question2: 'HUMAN LIFE: Where is your character from originally? What was their human life like?', question3: 'SIRE: What was your sire like? Describe your embrace or an early moment in your vampiric existence if you wish.', question4: 'CURRENT LIFE: How do you live your undead life? Where do you live? How do you obtain money? What’s your mode of transportation? Do you have a hobby or goal? Describe an average evening if you wish.', question5: 'CONNECTIONS: Are there are any people that you have strong connections to? A Ghoul? Mortal Family? Enemies? (Other PCs?)', question6: 'LAS VEGAS: How do you feel about King Cole and Las Vegas? The Psu’ho-wurv? The mortal government and crime families?', question7: 'CRYPTIDS: How do you feel about Cryptids? Are there any in particular you have met or been exposed to? Do you prefer to avoid them or have you just not had the chance?', question8: 'SPECIAL ATTENTION: What, if anything, is strange or unique about your character? Does he or she have any specific quirks or flaws? Is anything about your character (capabilities, background, or plans) unusual enough that the Storytellers need to pay special attention to it?'},
	{name: 'Ghoul', power_stat: nil, resource: 'Vitae', morality: 'Integrity', behavior_primary: 'Virtue', behavior_secondary: 'Vice', affiliation: 'Covenant', lineage: 'Clan', sublineage: nil, question1: 'AGE: How old are you? How old do you look? How long have you been a Ghoul? Other than the obvious, how has your life changed since you became a Ghoul?', question2: 'HUMAN LIFE: Where is your character from originally? What was their normal human life like?', question3: 'REGNANT: What is your Regnant like? Describe your relationship or an early moment in your undead existence if you wish.', question4: 'CURRENT LIFE: How do you live your new life? Where do you live? How do you obtain money? What’s your method of transportation? Do you have a hobby or goal? Describe an average evening if you wish.', question5: 'CONNECTIONS: Are there are any people that you have strong connections to? Another Ghoul? Mortal Family? Enemies? (Other PCs?)', question6: 'LAS VEGAS: How do you feel about King Cole and Las Vegas? The Psu’ho-wurv? The mortal government and crime families?', question7: 'CRYPTIDS: How do you feel about Cryptids? Are there any in particular you have met or been exposed to? Do you prefer to avoid them or have you just not had the chance?', question8: 'SPECIAL ATTENTION: What, if anything, is strange or unique about your character? Does he or she have any specific quirks or flaws? Is anything about your character (capabilities, background, or plans) unusual enough that the Storytellers need to pay special attention to it?'},
	{name: 'Mortal', power_stat: nil, resource: nil, morality: 'Integrity', behavior_primary: 'Virtue', behavior_secondary: 'Vice', affiliation: nil, lineage: nil, sublineage: nil, question1: 'NORMAL LIFE: How old are you? How do you live your life? Where do you live? How do you obtain money? What’s your method of transportation? Do you have a hobby or goal? Where is your character from originally? Describe an average evening if you wish.', question2: 'SUPERNATURAL: How did you find out about the supernatural? How long have you known about it? Is there anything you do not believe in? Describe an early interaction if you wish.', question3: 'SUPERNATURAL LIFE: What is your opinion of the supernatural? How do you feel it fits in with the world around you? Other than the obvious, how has your life changed since you found out how the world really works?', question4: 'VAMPIRES: Why do you choose to associate with Kindred Society? What do you gain from being around Vampires? What do you lose? What do they gain or lose?', question5: 'CONNECTIONS: Are there are any people that you have strong connections to? A Vampire or Ghoul? Family? Friends? Enemies? (Other PCs?)', question6: 'LAS VEGAS: How do you feel about Kindred society in Las Vegas? The mortal government and crime families?', question7: 'CRYPTIDS: How do you feel about Cryptids? Are there any in particular you have met or been exposed to? Do you prefer to avoid them or have you just not had the chance?', question8: 'SPECIAL ATTENTION: What, if anything, is strange or unique about your character? Does he or she have any specific quirks or flaws? Is anything about your character (capabilities, background, or plans) unusual enough that the Storytellers need to pay special attention to it?'},
	{name: 'Sin-Eater', power_stat: 'Psyche', resource: 'Plasm', morality: 'Synergy', behavior_primary: 'Calling', behavior_secondary: 'Craving', affiliation: nil, lineage: nil, sublineage: nil, question1: 'NORMAL LIFE: How old are you? How do you live your life? Where do you live? How do you obtain money? What’s your method of transportation? Do you have a hobby or goal? Where is your character from originally? Describe an average evening if you wish.', question2: 'THE BARGAIN: How did you die? What was meeting your Geist like? Why did you say yes to coming back? Other than the obvious, how has your life changed since you became Bound?', question3: 'YOUR GEIST: Describe your Geist. What is your opinion of it? How do you feel it fits in with the world around you? What does the Keystone look like?', question4: 'THE DEAD: What is your opinion on Ghosts and other Ephemeral entities? The Underworld? Describe an early experience with a shade or specter.', question5: 'VAMPIRES: Why do you choose to associate with Kindred Society? What do you gain from being around Vampires? What do you lose? What do they gain or lose? How do you feel about being a “Cryptid”?', question6: 'CONNECTIONS: Are there are any people that you have strong connections to? A Vampire or Ghoul? Family? Friends? Enemies? (Other PCs?)', question7: 'LAS VEGAS: How do you feel about Kindred society in Las Vegas? The mortal government and crime families?', question8: 'SPECIAL ATTENTION: What, if anything, is strange or unique about your character? Does he or she have any specific quirks or flaws? Is anything about your character (capabilities, background, or plans) unusual enough that the Storytellers need to pay special attention to it?'}
	])

power_types = PowerType.create([
	{name: 'Disciplines'},
	{name: 'Crúac Rituals'},
	{name: 'Scales of the Dragon'},
	{name: 'Theban Sorcery Rituals'},
	{name: 'Manifestations'},
	{name: 'Keys'},
	{name: 'Devotions'}
	])

power_groups = PowerGroup.create([
	{name: 'Animalism', power_type_id: 1},
	{name: 'Auspex', power_type_id: 1},
	{name: 'Celerity', power_type_id: 1},
	{name: 'Dominate', power_type_id: 1},
	{name: 'Majesty', power_type_id: 1},
	{name: 'Nightmare', power_type_id: 1},
	{name: 'Obfuscate', power_type_id: 1},
	{name: 'Protean', power_type_id: 1},
	{name: 'Resilience', power_type_id: 1},
	{name: 'Vigor', power_type_id: 1},
	{name: 'Coil of the Ascendant', power_type_id: 1},
	{name: 'Coil of the Wyrm', power_type_id: 1},
	{name: 'Coil of the Voivode', power_type_id: 1},
	{name: 'Crúac', power_type_id: 1},
	{name: 'Theban Sorcery', power_type_id: 1},
	{name: 'The Boneyard', power_type_id: 5},
	{name: 'The Caul', power_type_id: 5},
	{name: 'The Pale', power_type_id: 5},
	{name: 'The Monument', power_type_id: 5},
	{name: 'Keys', power_type_id: 6},
	{name: 'Theban Sorcery 1', power_type_id: 4},
	{name: 'Theban Sorcery 2', power_type_id: 4},
	{name: 'Theban Sorcery 3', power_type_id: 4},
	{name: 'Theban Sorcery 4', power_type_id: 4},
	{name: 'Theban Sorcery 5', power_type_id: 4},
	{name: 'Crúac 1', power_type_id: 2},
	{name: 'Crúac 2', power_type_id: 2},
	{name: 'Crúac 3', power_type_id: 2},
	{name: 'Crúac 4', power_type_id: 2},
	{name: 'Crúac 5', power_type_id: 2},
	{name: 'Mystery of the Ascendant', power_type_id: 3},
	{name: 'Mystery of the Wyrm', power_type_id: 3},
	{name: 'Mystery of the Voivode', power_type_id: 3},
	{name: 'Atomics', power_type_id: 1},
	{name: 'General', power_type_id: 7},
	{name: 'Sangmelier', power_type_id: 7},
	{name: 'Showmen', power_type_id: 7},
	{name: 'Psu\'ho-wurv', power_type_id: 7}
	])

powers = Power.create([
	{name: 'Feral Whispers', rating: 1, power_group_id: 1},
	{name: 'Raise the Familiar', rating: 2, power_group_id: 1},
	{name: 'Summon the Hunt', rating: 3, power_group_id: 1},
	{name: 'Feral Infection', rating: 4, power_group_id: 1},
	{name: 'Lord of the Land', rating: 5, power_group_id: 1},
	{name: 'Beast\'s Hackles', rating: 1, power_group_id: 2},
	{name: 'Uncanny Perception', rating: 2, power_group_id: 2},
	{name: 'The Spirit\'s Touch', rating: 3, power_group_id: 2},
	{name: 'Lay Open the Mind', rating: 4, power_group_id: 2},
	{name: 'Twilight Projection', rating: 5, power_group_id: 2},
	{name: 'Celerity 1', rating: 1, power_group_id: 3},
	{name: 'Celerity 2', rating: 2, power_group_id: 3},
	{name: 'Celerity 3', rating: 3, power_group_id: 3},
	{name: 'Celerity 4', rating: 4, power_group_id: 3},
	{name: 'Celerity 5', rating: 5, power_group_id: 3},
	{name: 'Mesmerize', rating: 1, power_group_id: 4},
	{name: 'Iron Edict', rating: 2, power_group_id: 4},
	{name: 'Entombed Command', rating: 3, power_group_id: 4},
	{name: 'The Lying Mind', rating: 4, power_group_id: 4},
	{name: 'Possession', rating: 5, power_group_id: 4},
	{name: 'Awe', rating: 1, power_group_id: 5},
	{name: 'Confidant', rating: 2, power_group_id: 5},
	{name: 'Green Eyes', rating: 3, power_group_id: 5},
	{name: 'Loyalty', rating: 4, power_group_id: 5},
	{name: 'Idol', rating: 5, power_group_id: 5},
	{name: 'Dread Presence', rating: 1, power_group_id: 6},
	{name: 'Face of the Beast', rating: 2, power_group_id: 6},
	{name: 'The Grand Delusion', rating: 3, power_group_id: 6},
	{name: 'Waking Nightmare', rating: 4, power_group_id: 6},
	{name: 'Mortal Terror', rating: 5, power_group_id: 6},
	{name: 'Face in the Crowd', rating: 1, power_group_id: 7},
	{name: 'Touch of Shadow', rating: 2, power_group_id: 7},
	{name: 'Cloak of Night', rating: 3, power_group_id: 7},
	{name: 'The Familiar Stranger', rating: 4, power_group_id: 7},
	{name: 'Oubliette', rating: 5, power_group_id: 7},
	{name: 'Face in the Crowd', rating: 1, power_group_id: 7},
	{name: 'Unmarked Grave', rating: 1, power_group_id: 8},
	{name: 'Predatory Aspect', rating: 2, power_group_id: 8},
	{name: 'Beast\'s Skin', rating: 3, power_group_id: 8},
	{name: 'Unnatural Aspect', rating: 4, power_group_id: 8},
	{name: 'Primeval Miasma', rating: 5, power_group_id: 8},
	{name: 'Resilience 1', rating: 1, power_group_id: 9},
	{name: 'Resilience 2', rating: 2, power_group_id: 9},
	{name: 'Resilience 3', rating: 3, power_group_id: 9},
	{name: 'Resilience 4', rating: 4, power_group_id: 9},
	{name: 'Resilience 5', rating: 5, power_group_id: 9},
	{name: 'Vigor 1', rating: 1, power_group_id: 10},
	{name: 'Vigor 2', rating: 2, power_group_id: 10},
	{name: 'Vigor 3', rating: 3, power_group_id: 10},
	{name: 'Vigor 4', rating: 4, power_group_id: 10},
	{name: 'Vigor 5', rating: 5, power_group_id: 10},
	{name: 'Surmounting the Daysleep', rating: 1, power_group_id: 11},
	{name: 'The Warm Face', rating: 2, power_group_id: 11},
	{name: 'Conquer the Red Fear', rating: 3, power_group_id: 11},
	{name: 'Peace with the Flame', rating: 4, power_group_id: 11},
	{name: 'Sun\'s Forgotten Kiss', rating: 5, power_group_id: 11},
	{name: 'Stir the Beast', rating: 1, power_group_id: 12},
	{name: 'Beast\'s Hunger', rating: 2, power_group_id: 12},
	{name: 'Leash the Beast', rating: 3, power_group_id: 12},
	{name: 'Beast\'s Power', rating: 4, power_group_id: 12},
	{name: 'Eternal Frenzy', rating: 5, power_group_id: 12},
	{name: 'Taste of Fealty', rating: 1, power_group_id: 13},
	{name: 'Into the Fold', rating: 2, power_group_id: 13},
	{name: 'Call to Serve', rating: 3, power_group_id: 13},
	{name: 'Voivode Undisputed', rating: 4, power_group_id: 13},
	{name: 'The Vast Dynasty', rating: 5, power_group_id: 13},
	{name: 'Crúac 1', rating: 1, power_group_id: 14},
	{name: 'Crúac 2', rating: 2, power_group_id: 14},
	{name: 'Crúac 3', rating: 3, power_group_id: 14},
	{name: 'Crúac 4', rating: 4, power_group_id: 14},
	{name: 'Crúac 5', rating: 5, power_group_id: 14},
	{name: 'Theban Sorcery 1', rating: 1, power_group_id: 15},
	{name: 'Theban Sorcery 2', rating: 2, power_group_id: 15},
	{name: 'Theban Sorcery 3', rating: 3, power_group_id: 15},
	{name: 'Theban Sorcery 4', rating: 4, power_group_id: 15},
	{name: 'Theban Sorcery 5', rating: 5, power_group_id: 15},
	{name: 'Ethereal Forge', rating: 1, power_group_id: 16},
	{name: 'Marionette', rating: 1, power_group_id: 16},
	{name: 'Graveyard Mien', rating: 1, power_group_id: 16},
	{name: 'Telekinesis', rating: 1, power_group_id: 16},
	{name: 'Nightmares', rating: 1, power_group_id: 16},
	{name: 'Form of the Reaper', rating: 1, power_group_id: 17},
	{name: 'Cloak of Twilight', rating: 1, power_group_id: 17},
	{name: 'Form of the Abattoir', rating: 1, power_group_id: 17},
	{name: 'Reverse the Inevitable', rating: 1, power_group_id: 17},
	{name: 'Ghost in the Machine', rating: 1, power_group_id: 17},
	{name: 'Dual Existence', rating: 1, power_group_id: 18},
	{name: 'Twilight Familiar', rating: 1, power_group_id: 18},
	{name: 'Twilight Curse', rating: 1, power_group_id: 18},
	{name: 'The Risen Hunger', rating: 1, power_group_id: 18},
	{name: 'The Liar\'s Key', rating: 1, power_group_id: 18},
	{name: 'Stir the Living', rating: 1, power_group_id: 19},
	{name: 'Overclock', rating: 1, power_group_id: 19},
	{name: 'Uplifting Voice', rating: 1, power_group_id: 19},
	{name: 'Dead Mask', rating: 1, power_group_id: 19},
	{name: 'Cthonian Pact', rating: 1, power_group_id: 19},
	{name: 'Cold-Wind', rating: 1, power_group_id: 20},
	{name: 'Grave-Dirt', rating: 1, power_group_id: 20},
	{name: 'Industrial', rating: 1, power_group_id: 20},
	{name: 'Passionate', rating: 1, power_group_id: 20},
	{name: 'Phantasmal', rating: 1, power_group_id: 20},
	{name: 'Primeval', rating: 1, power_group_id: 20},
	{name: 'Pyre-Flame', rating: 1, power_group_id: 20},
	{name: 'Stigmata', rating: 1, power_group_id: 20},
	{name: 'Stillness', rating: 1, power_group_id: 20},
	{name: 'Tear-Stained', rating: 1, power_group_id: 20},
	{name: 'Blood Scourge', rating: 1, power_group_id: 21},
	{name: 'Vitae Reliquary', rating: 1, power_group_id: 21},
	{name: 'Hauberk of Blood', rating: 1, power_group_id: 21},
	{name: 'Curse of Babel', rating: 2, power_group_id: 22},
	{name: 'Liar\'s Plague', rating: 2, power_group_id: 22},
	{name: 'Blandishment of Sin', rating: 3, power_group_id: 23},
	{name: 'Malediction of Despair', rating: 3, power_group_id: 23},
	{name: 'Gift of Lazarus', rating: 4, power_group_id: 24},
	{name: 'Stigmata', rating: 4, power_group_id: 24},
	{name: 'Transubstantiation', rating: 5, power_group_id: 25},
	{name: 'Pangs of Proserpina', rating: 1, power_group_id: 26},
	{name: 'Rigor Mortis', rating: 1, power_group_id: 26},
	{name: 'Maiden, Mother, Crone', rating: 1, power_group_id: 26},
	{name: 'Cheval', rating: 2, power_group_id: 27},
	{name: 'The Hydra\'s Vitae', rating: 2, power_group_id: 27},
	{name: 'Deflection of Wooden Doom', rating: 3, power_group_id: 28},
	{name: 'Touch of the Morrigan', rating: 3, power_group_id: 28},
	{name: 'Blood Price', rating: 4, power_group_id: 29},
	{name: 'Willful Vitae', rating: 4, power_group_id: 29},
	{name: 'Blood Blight', rating: 4, power_group_id: 29},
	{name: 'Feeding the Crone', rating: 4, power_group_id: 30},
	{name: 'Day-Wake Conditioning', rating: 1, power_group_id: 31},
	{name: 'Epidermal Shielding Bath', rating: 1, power_group_id: 31},
	{name: 'Flesh Graft Treatment', rating: 1, power_group_id: 31},
	{name: 'Augmented Vitae Draught', rating: 1, power_group_id: 32},
	{name: 'Kindred Sense Endowment', rating: 1, power_group_id: 32},
	{name: 'Surgical Heart Removal', rating: 1, power_group_id: 32},
	{name: 'Blood Cleansing Ritual', rating: 1, power_group_id: 33},
	{name: 'Fealty\'s Reward', rating: 1, power_group_id: 33},
	{name: 'Mass Embrace', rating: 1, power_group_id: 33},
	{name: 'Sanguinary Invigoration', rating: 1, power_group_id: 33},
	{name: 'Consume the Living', rating: 1, power_group_id: 36},
	{name: 'Hungry Maw', rating: 1, power_group_id: 36},
	{name: 'Large Appetites', rating: 1, power_group_id: 36},
	{name: 'Blood Wine', rating: 1, power_group_id: 36},
	{name: 'Feast of Ages', rating: 1, power_group_id: 36},
	{name: 'Discerning Tastes', rating: 1, power_group_id: 36},
	{name: 'Adoring Fans', rating: 1, power_group_id: 37},
	{name: 'Special Effects', rating: 1, power_group_id: 37},
	{name: 'Geiger Counter', rating: 1, power_group_id: 38},
	{name: 'Salt the Earth', rating: 1, power_group_id: 38},
	{name: 'Tolerance', rating: 1, power_group_id: 34},
	{name: 'Grasp of Decay', rating: 2, power_group_id: 34},
	{name: 'Disrupt the Flow', rating: 3, power_group_id: 34},
	{name: 'Thermal Bath', rating: 4, power_group_id: 34},
	{name: 'I Am Become Death...', rating: 5, power_group_id: 34}
	])

character_type_has_power_type = CharacterTypeHasPowerType.create([
	{character_type_id: 1, power_type_id: 1},
	{character_type_id: 1, power_type_id: 2},
	{character_type_id: 1, power_type_id: 3},
	{character_type_id: 1, power_type_id: 4},
	{character_type_id: 2, power_type_id: 1},
	{character_type_id: 4, power_type_id: 5}
	])

lineages = Lineage.create([
	{name: 'Daeva'},
	{name: 'Gangrel'},
	{name: 'Mekhet'},
	{name: 'Nosferatu'},
	{name: 'Ventrue'}
	])

affiliations = Affiliation.create([
	{name: 'Carthian Movement'},
	{name: 'Circle of the Crone'},
	{name: 'Invictus'},
	{name: 'Lancea et Sanctum'},
	{name: 'Ordo Dracul'},
	{name: 'Unaligned'}
	])

character_type_has_lineages = CharacterTypeHasLineage.create([
	{character_type_id: 1, lineage_id: 1},
	{character_type_id: 1, lineage_id: 2},
	{character_type_id: 1, lineage_id: 3},
	{character_type_id: 1, lineage_id: 4},
	{character_type_id: 1, lineage_id: 5},
	{character_type_id: 2, lineage_id: 1},
	{character_type_id: 2, lineage_id: 2},
	{character_type_id: 2, lineage_id: 3},
	{character_type_id: 2, lineage_id: 4},
	{character_type_id: 2, lineage_id: 5}
	])

character_type_has_affiliations = CharacterTypeHasAffiliation.create([
	{character_type_id: 1, affiliation_id: 1},
	{character_type_id: 1, affiliation_id: 2},
	{character_type_id: 1, affiliation_id: 3},
	{character_type_id: 1, affiliation_id: 4},
	{character_type_id: 1, affiliation_id: 5},
	{character_type_id: 1, affiliation_id: 6},
	{character_type_id: 2, affiliation_id: 1},
	{character_type_id: 2, affiliation_id: 2},
	{character_type_id: 2, affiliation_id: 3},
	{character_type_id: 2, affiliation_id: 4},
	{character_type_id: 2, affiliation_id: 5},
	{character_type_id: 2, affiliation_id: 6}
	])

behavior_primaries = BehaviorPrimary.create([
	{name: 'Authoritarian'},
	{name: 'Child'},
	{name: 'Competitor'},
	{name: 'Conformist'},
	{name: 'Conspirator'},
	{name: 'Courtesan'},
	{name: 'Cult Leader'},
	{name: 'Deviant'},
	{name: 'Follower'},
	{name: 'Guru'},
	{name: 'Idealist'},
	{name: 'Jester'},
	{name: 'Junkie'},
	{name: 'Martyr'},
	{name: 'Masochist'},
	{name: 'Monster'},
	{name: 'Nomad'},
	{name: 'Nurturer'},
	{name: 'Perfectionist'},
	{name: 'Penitent'},
	{name: 'Questioner'},
	{name: 'Rebel'},
	{name: 'Scholar'},
	{name: 'Social Chameleon'},
	{name: 'Soldier'},
	{name: 'Spy'},
	{name: 'Survivor'},
	{name: 'Visionary'},
	{name: 'Hopeful'},
	{name: 'Loving'},
	{name: 'Honest'},
	{name: 'Humble'},
	{name: 'Ambitious'},
	{name: 'Trustworthy'},
	{name: 'Loyal'},
	{name: 'Just'},
	{name: 'Peaceful'},
	{name: 'Generous'},
	{name: 'Righteous'},
	{name: 'Courageous'},
	{name: 'Patient'},
	{name: 'Advocate'},
	{name: 'Celebrant'},
	{name: 'Gatekeeper'},
	{name: 'Mourner'},
	{name: 'Necromancer'},
	{name: 'Nostalgic'},
	{name: 'Pilgrim'},
	{name: 'Reaper'}
	])

behavior_secondaries = BehaviorSecondary.create([
	{name: 'Authoritarian'},
	{name: 'Child'},
	{name: 'Competitor'},
	{name: 'Conformist'},
	{name: 'Conspirator'},
	{name: 'Courtesan'},
	{name: 'Cult Leader'},
	{name: 'Deviant'},
	{name: 'Follower'},
	{name: 'Guru'},
	{name: 'Idealist'},
	{name: 'Jester'},
	{name: 'Junkie'},
	{name: 'Martyr'},
	{name: 'Masochist'},
	{name: 'Monster'},
	{name: 'Nomad'},
	{name: 'Nurturer'},
	{name: 'Perfectionist'},
	{name: 'Penitent'},
	{name: 'Questioner'},
	{name: 'Rebel'},
	{name: 'Scholar'},
	{name: 'Social Chameleon'},
	{name: 'Soldier'},
	{name: 'Spy'},
	{name: 'Survivor'},
	{name: 'Visionary'},
	{name: 'Pessimistic'},
	{name: 'Hateful'},
	{name: 'Deceitful'},
	{name: 'Arrogant'},
	{name: 'Ambitious'},
	{name: 'Treacherous'},
	{name: 'Untrustworthy'},
	{name: 'Cruel'},
	{name: 'Violent'},
	{name: 'Greedy'},
	{name: 'Corrupt'},
	{name: 'Cowardly'},
	{name: 'Hasty'},
	{name: 'Acedia'},
	{name: 'Attention'},
	{name: 'Appetite'},
	{name: 'Narcotics'},
	{name: 'Revenge'},
	{name: 'Objects'},
	{name: 'Secrets'},
	{name: 'Violence'}
	])

character_type_has_behavior_primaries = CharacterTypeHasBehaviorPrimary.create([
	{character_type_id: 1, behavior_primary_id: 1},
	{character_type_id: 1, behavior_primary_id: 2},
	{character_type_id: 1, behavior_primary_id: 3},
	{character_type_id: 1, behavior_primary_id: 4},
	{character_type_id: 1, behavior_primary_id: 5},
	{character_type_id: 1, behavior_primary_id: 6},
	{character_type_id: 1, behavior_primary_id: 7},
	{character_type_id: 1, behavior_primary_id: 8},
	{character_type_id: 1, behavior_primary_id: 9},
	{character_type_id: 1, behavior_primary_id: 10},
	{character_type_id: 1, behavior_primary_id: 11},
	{character_type_id: 1, behavior_primary_id: 12},
	{character_type_id: 1, behavior_primary_id: 13},
	{character_type_id: 1, behavior_primary_id: 14},
	{character_type_id: 1, behavior_primary_id: 15},
	{character_type_id: 1, behavior_primary_id: 16},
	{character_type_id: 1, behavior_primary_id: 17},
	{character_type_id: 1, behavior_primary_id: 18},
	{character_type_id: 1, behavior_primary_id: 19},
	{character_type_id: 1, behavior_primary_id: 20},
	{character_type_id: 1, behavior_primary_id: 21},
	{character_type_id: 1, behavior_primary_id: 22},
	{character_type_id: 1, behavior_primary_id: 23},
	{character_type_id: 1, behavior_primary_id: 24},
	{character_type_id: 1, behavior_primary_id: 25},
	{character_type_id: 1, behavior_primary_id: 26},
	{character_type_id: 1, behavior_primary_id: 27},
	{character_type_id: 1, behavior_primary_id: 28},
	{character_type_id: 2, behavior_primary_id: 29},
	{character_type_id: 2, behavior_primary_id: 30},
	{character_type_id: 2, behavior_primary_id: 31},
	{character_type_id: 2, behavior_primary_id: 32},
	{character_type_id: 2, behavior_primary_id: 33},
	{character_type_id: 2, behavior_primary_id: 34},
	{character_type_id: 2, behavior_primary_id: 35},
	{character_type_id: 2, behavior_primary_id: 36},
	{character_type_id: 2, behavior_primary_id: 37},
	{character_type_id: 2, behavior_primary_id: 38},
	{character_type_id: 2, behavior_primary_id: 39},
	{character_type_id: 2, behavior_primary_id: 40},
	{character_type_id: 2, behavior_primary_id: 41},
	{character_type_id: 3, behavior_primary_id: 29},
	{character_type_id: 3, behavior_primary_id: 30},
	{character_type_id: 3, behavior_primary_id: 31},
	{character_type_id: 3, behavior_primary_id: 32},
	{character_type_id: 3, behavior_primary_id: 33},
	{character_type_id: 3, behavior_primary_id: 34},
	{character_type_id: 3, behavior_primary_id: 35},
	{character_type_id: 3, behavior_primary_id: 36},
	{character_type_id: 3, behavior_primary_id: 37},
	{character_type_id: 3, behavior_primary_id: 38},
	{character_type_id: 3, behavior_primary_id: 39},
	{character_type_id: 3, behavior_primary_id: 40},
	{character_type_id: 3, behavior_primary_id: 41},
	{character_type_id: 4, behavior_primary_id: 42},
	{character_type_id: 4, behavior_primary_id: 43},
	{character_type_id: 4, behavior_primary_id: 44},
	{character_type_id: 4, behavior_primary_id: 45},
	{character_type_id: 4, behavior_primary_id: 46},
	{character_type_id: 4, behavior_primary_id: 47},
	{character_type_id: 4, behavior_primary_id: 48},
	{character_type_id: 4, behavior_primary_id: 49}
	])

character_type_has_behavior_secondaries = CharacterTypeHasBehaviorSecondary.create([
	{character_type_id: 1, behavior_secondary_id: 1},
	{character_type_id: 1, behavior_secondary_id: 2},
	{character_type_id: 1, behavior_secondary_id: 3},
	{character_type_id: 1, behavior_secondary_id: 4},
	{character_type_id: 1, behavior_secondary_id: 5},
	{character_type_id: 1, behavior_secondary_id: 6},
	{character_type_id: 1, behavior_secondary_id: 7},
	{character_type_id: 1, behavior_secondary_id: 8},
	{character_type_id: 1, behavior_secondary_id: 9},
	{character_type_id: 1, behavior_secondary_id: 10},
	{character_type_id: 1, behavior_secondary_id: 11},
	{character_type_id: 1, behavior_secondary_id: 12},
	{character_type_id: 1, behavior_secondary_id: 13},
	{character_type_id: 1, behavior_secondary_id: 14},
	{character_type_id: 1, behavior_secondary_id: 15},
	{character_type_id: 1, behavior_secondary_id: 16},
	{character_type_id: 1, behavior_secondary_id: 17},
	{character_type_id: 1, behavior_secondary_id: 18},
	{character_type_id: 1, behavior_secondary_id: 19},
	{character_type_id: 1, behavior_secondary_id: 20},
	{character_type_id: 1, behavior_secondary_id: 21},
	{character_type_id: 1, behavior_secondary_id: 22},
	{character_type_id: 1, behavior_secondary_id: 23},
	{character_type_id: 1, behavior_secondary_id: 24},
	{character_type_id: 1, behavior_secondary_id: 25},
	{character_type_id: 1, behavior_secondary_id: 26},
	{character_type_id: 1, behavior_secondary_id: 27},
	{character_type_id: 1, behavior_secondary_id: 28},
	{character_type_id: 2, behavior_secondary_id: 29},
	{character_type_id: 2, behavior_secondary_id: 30},
	{character_type_id: 2, behavior_secondary_id: 31},
	{character_type_id: 2, behavior_secondary_id: 32},
	{character_type_id: 2, behavior_secondary_id: 33},
	{character_type_id: 2, behavior_secondary_id: 34},
	{character_type_id: 2, behavior_secondary_id: 35},
	{character_type_id: 2, behavior_secondary_id: 36},
	{character_type_id: 2, behavior_secondary_id: 37},
	{character_type_id: 2, behavior_secondary_id: 38},
	{character_type_id: 2, behavior_secondary_id: 39},
	{character_type_id: 2, behavior_secondary_id: 40},
	{character_type_id: 2, behavior_secondary_id: 41},
	{character_type_id: 3, behavior_secondary_id: 29},
	{character_type_id: 3, behavior_secondary_id: 30},
	{character_type_id: 3, behavior_secondary_id: 31},
	{character_type_id: 3, behavior_secondary_id: 32},
	{character_type_id: 3, behavior_secondary_id: 33},
	{character_type_id: 3, behavior_secondary_id: 34},
	{character_type_id: 3, behavior_secondary_id: 35},
	{character_type_id: 3, behavior_secondary_id: 36},
	{character_type_id: 3, behavior_secondary_id: 37},
	{character_type_id: 3, behavior_secondary_id: 38},
	{character_type_id: 3, behavior_secondary_id: 39},
	{character_type_id: 3, behavior_secondary_id: 40},
	{character_type_id: 3, behavior_secondary_id: 41},
	{character_type_id: 4, behavior_secondary_id: 42},
	{character_type_id: 4, behavior_secondary_id: 43},
	{character_type_id: 4, behavior_secondary_id: 44},
	{character_type_id: 4, behavior_secondary_id: 45},
	{character_type_id: 4, behavior_secondary_id: 46},
	{character_type_id: 4, behavior_secondary_id: 47},
	{character_type_id: 4, behavior_secondary_id: 48},
	{character_type_id: 4, behavior_secondary_id: 49}
	])

attribute_categories = AttributeCategory.create([
	{name: 'Mental'},
	{name: 'Physical'},
	{name: 'Social'}
	])

skill_categories = SkillCategory.create([
	{name: 'Mental'},
	{name: 'Physical'},
	{name: 'Social'}
	])

attribs = Attrib.create([
	{name: 'Intelligence', attribute_category_id: 1},
	{name: 'Wits', attribute_category_id: 1},
	{name: 'Resolve', attribute_category_id: 1},
	{name: 'Strength', attribute_category_id: 2},
	{name: 'Dexterity', attribute_category_id: 2},
	{name: 'Stamina', attribute_category_id: 2},
	{name: 'Presence', attribute_category_id: 3},
	{name: 'Manipulation', attribute_category_id: 3},
	{name: 'Composure', attribute_category_id: 3}
	])

skills = Skill.create([
	{name: 'Academics', skill_category_id: 1},
	{name: 'Computer', skill_category_id: 1},
	{name: 'Crafts', skill_category_id: 1},
	{name: 'Investigation', skill_category_id: 1},
	{name: 'Medicine', skill_category_id: 1},
	{name: 'Occult', skill_category_id: 1},
	{name: 'Politics', skill_category_id: 1},
	{name: 'Science', skill_category_id: 1},
	{name: 'Athletics', skill_category_id: 2},
	{name: 'Brawl', skill_category_id: 2},
	{name: 'Drive', skill_category_id: 2},
	{name: 'Firearms', skill_category_id: 2},
	{name: 'Larceny', skill_category_id: 2},
	{name: 'Stealth', skill_category_id: 2},
	{name: 'Survival', skill_category_id: 2},
	{name: 'Weaponry', skill_category_id: 2},
	{name: 'Animal Ken', skill_category_id: 3},
	{name: 'Empathy', skill_category_id: 3},
	{name: 'Expression', skill_category_id: 3},
	{name: 'Intimidation', skill_category_id: 3},
	{name: 'Persuasion', skill_category_id: 3},
	{name: 'Socialize', skill_category_id: 3},
	{name: 'Streetwise', skill_category_id: 3},
	{name: 'Subterfuge', skill_category_id: 3},
	])

merit_categories = MeritCategory.create([
	{merit_category: 'General'},
	{merit_category: 'Ghoul'},
	{merit_category: 'Mortal'},
	{merit_category: 'Sin-Eater'},
	{merit_category: 'Carthian Law'},
	{merit_category: 'Invictus Oaths'},
	{merit_category: 'Sangmellier'},
	{merit_category: 'Showmen'},
	{merit_category: 'Psu\'ho-wurv'}
	])

merits = Merit.create([
	{name: 'Acute Senses', allowed_ratings: '[1]', has_specification: false, has_description: false},
	{name: 'Allies', allowed_ratings: '[1,2,3,4,5]', has_specification: true, has_description: true},
	{name: 'Alternate Identity', allowed_ratings: '[1,2,3]', has_specification: true, has_description: true},
	{name: 'Altar', allowed_ratings: '[3]', has_specification: false, has_description: false},
	{name: 'Anointed', allowed_ratings: '[2]', has_specification: false, has_description: false},
	{name: 'Anonymity', allowed_ratings: '[1,2,3,4,5]', has_specification: false, has_description: false},
	{name: 'Area of Expertise', allowed_ratings: '[1]', has_specification: true, has_description: false},
	{name: 'Attaché', allowed_ratings: '[1,2,3,4,5]', has_specification: true, has_description: true},
	{name: 'Barfly', allowed_ratings: '[2]', has_specification: false, has_description: false},
	{name: 'Bloodhound', allowed_ratings: '[2]', has_specification: false, has_description: false},
	{name: 'Bloodline Membership', allowed_ratings: '[2]', has_specification: true, has_description: false},
	{name: 'Cacophony Savvy', allowed_ratings: '[1,2,3]', has_specification: false, has_description: false},
	{name: 'Carthian Pull', allowed_ratings: '[1]', has_specification: false, has_description: false},
	{name: 'Casino', allowed_ratings: '[1]', has_specification: false, has_description: false},
	{name: 'Claws of the Unholy', allowed_ratings: '[1]', has_specification: false, has_description: false},
	{name: 'Close Family', allowed_ratings: '[1]', has_specification: false, has_description: false},
	{name: 'Common Sense', allowed_ratings: '[3]', has_specification: false, has_description: false},
	{name: 'Contacts', allowed_ratings: '[1]', has_specification: true, has_description: false},
	{name: 'Crack Driver', allowed_ratings: '[2,3]', has_specification: false, has_description: false},
	{name: 'Devoted', allowed_ratings: '[3]', has_specification: true, has_description: false},
	{name: 'Distinguished Palate', allowed_ratings: '[1]', has_specification: false, has_description: false},
	{name: 'Double-Jointed', allowed_ratings: '[2]', has_specification: false, has_description: false},
	{name: 'Dynasty Membership', allowed_ratings: '[1,2,3]', has_specification: true, has_description: false},
	{name: 'Fame', allowed_ratings: '[1,2,3]', has_specification: true, has_description: false},
	{name: 'Feeding Grounds', allowed_ratings: '[1,2,3,4,5]', has_specification: true, has_description: true},
	{name: 'Fleet of Foot', allowed_ratings: '[1,2,3]', has_specification: false, has_description: false},
	{name: 'Herd', allowed_ratings: '[1,2,3,4,5]', has_specification: true, has_description: false},
	{name: 'Hobbyist Clique', allowed_ratings: '[2]', has_specification: true, has_description: false},
	{name: 'Honey Trap', allowed_ratings: '[1]', has_specification: false, has_description: false},
	{name: 'I Know a Guy', allowed_ratings: '[1]', has_specification: false, has_description: false},
	{name: 'Indomitable', allowed_ratings: '[2]', has_specification: false, has_description: false},
	{name: 'Inspiring', allowed_ratings: '[3]', has_specification: false, has_description: false},
	{name: 'Interdisciplinary Specialty', allowed_ratings: '[1]', has_specification: true, has_description: false},
	{name: 'Invested', allowed_ratings: '[1]', has_specification: false, has_description: false},
	{name: 'Iron Will', allowed_ratings: '[2]', has_specification: false, has_description: false},
	{name: 'Kindred Dueling (Style)', allowed_ratings: '[1,2,3,4,5]', has_specification: false, has_description: false},
	{name: 'Language', allowed_ratings: '[1]', has_specification: true, has_description: false},
	{name: 'Library', allowed_ratings: '[1,2,3]', has_specification: true, has_description: false},
	{name: 'Lorekeeper', allowed_ratings: '[1]', has_specification: false, has_description: false},
	{name: 'Mentor', allowed_ratings: '[1,2,3,4,5]', has_specification: true, has_description: true},
	{name: 'Mystery Cult Initiation', allowed_ratings: '[1,2,3,4,5]', has_specification: true, has_description: true},
	{name: 'Night Doctor Surgery', allowed_ratings: '[3]', has_specification: false, has_description: false},
	{name: 'Of Rose and Thorn (Style)', allowed_ratings: '[2,3,4]', has_specification: false, has_description: false},
	{name: 'Pack Alpha', allowed_ratings: '[1]', has_specification: false, has_description: false},
	{name: 'Parkour', allowed_ratings: '[1,2,3,4,5]', has_specification: false, has_description: false},
	{name: 'Pilot\'s License', allowed_ratings: '[1]', has_specification: false, has_description: false},
	{name: 'Resources', allowed_ratings: '[1,2,3,4,5]', has_specification: false, has_description: false},
	{name: 'Retainer', allowed_ratings: '[1,2,3,4,5]', has_specification: true, has_description: true},
	{name: 'Riding the Wave', allowed_ratings: '[1,2,3,4,5]', has_specification: false, has_description: false},
	{name: 'Safe Place', allowed_ratings: '[1,2,3,4,5]', has_specification: true, has_description: false},
	{name: 'Secret Society Junkie', allowed_ratings: '[1]', has_specification: false, has_description: false},
	{name: 'Sleight of Hand', allowed_ratings: '[2]', has_specification: false, has_description: false},
	{name: 'Social Engineering', allowed_ratings: '[4]', has_specification: false, has_description: false},
	{name: 'Staff', allowed_ratings: '[1]', has_specification: true, has_description: false},
	{name: 'Status', allowed_ratings: '[1,2,3,4,5]', has_specification: true, has_description: false},
	{name: 'Striking Looks', allowed_ratings: '[1,2]', has_specification: false, has_description: false},
	{name: 'Speaker for the Silent', allowed_ratings: '[3]', has_specification: false, has_description: false},
	{name: 'Swarm Form', allowed_ratings: '[2]', has_specification: false, has_description: false},
	{name: 'Sworn', allowed_ratings: '[1]', has_specification: true, has_description: false},
	{name: 'Taste', allowed_ratings: '[1]', has_specification: false, has_description: false},
	{name: 'Trained Observer', allowed_ratings: '[1,3]', has_specification: false, has_description: false},
	{name: 'Unnatural Affinity', allowed_ratings: '[1,2,3,4,5]', has_specification: false, has_description: false},
	{name: 'Unsettling Gaze', allowed_ratings: '[1]', has_specification: false, has_description: false},
	{name: 'Where the Bodies Are Buried', allowed_ratings: '[2]', has_specification: false, has_description: false},
	{name: 'Taste of Shadow', allowed_ratings: '[2]', has_specification: false, has_description: false},
	{name: 'Taste of the Serpent', allowed_ratings: '[2]', has_specification: false, has_description: false},
	{name: 'Taste of the Wild', allowed_ratings: '[2]', has_specification: false, has_description: false},
	{name: 'Taste of Gold', allowed_ratings: '[2]', has_specification: false, has_description: false},
	{name: 'Taste of Fear', allowed_ratings: '[2]', has_specification: false, has_description: false},
	{name: 'Beast Whisperer', allowed_ratings: '[2]', has_specification: false, has_description: false},
	{name: 'Empowered to Speak', allowed_ratings: '[1]', has_specification: false, has_description: false},
	{name: 'Protector', allowed_ratings: '[2]', has_specification: false, has_description: false},
	{name: 'Source Sympathy', allowed_ratings: '[1]', has_specification: false, has_description: false},
	{name: 'Vitae Hound', allowed_ratings: '[2]', has_specification: false, has_description: false},
	{name: 'Watch Dog', allowed_ratings: '[2]', has_specification: false, has_description: false},
	{name: 'Clear-Sighted', allowed_ratings: '[2]', has_specification: false, has_description: false},
	{name: 'Producer', allowed_ratings: '[1]', has_specification: false, has_description: false},
	{name: 'Tolerance for Biology', allowed_ratings: '[1]', has_specification: false, has_description: false},
	{name: 'Unseen Sense', allowed_ratings: '[2]', has_specification: false, has_description: false},
	{name: 'Weakened Bond', allowed_ratings: '[3]', has_specification: false, has_description: false},
	{name: 'Ancient Memories', allowed_ratings: '[1,3,5]', has_specification: false, has_description: false},
	{name: 'Call Keystone', allowed_ratings: '[1]', has_specification: false, has_description: false},
	{name: 'Ghostly Serf', allowed_ratings: '[5]', has_specification: true, has_description: true},
	{name: 'Haunt', allowed_ratings: '[1,2,3,4,5]', has_specification: true, has_description: false},
	{name: 'Memento', allowed_ratings: '[1]', has_specification: true, has_description: true},
	{name: 'Twilight Network', allowed_ratings: '[1,2,3]', has_specification: false, has_description: false}
	])